name: test

on:
  push:
    branches: [develop, main, master, "feature/**"]
  pull_request:
    branches: [develop, main, master, "feature/**"]

  # Allows workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run RSpec
        run: bundle exec rspec
